development:
  adapter: mysql2
  database: bugzilla_development
  username: root
  password: root
  host: localhost
test:
  adapter: mysql2
  database: bugzilla_test
  username: root
  password: root
  host: localhost
production:
  adapter: mysql2
  database: bugzilla_production
  username: root
  password: root
  host: localhost


